const { GoogleGenerativeAI } = require('@google/generative-ai');

let geminiClient;
let model;

// Initialize Gemini client only if API key is available
if (process.env.GEMINI_API_KEY) {
  geminiClient = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  model = geminiClient.getGenerativeModel({ model: 'gemini-2.5-flash' });
}

/**
 * Generate AI-enhanced ideas using Gemini
 * @param {Array} notes - User's notes
 * @param {Array} localIdeas - Ideas generated by local algorithm
 * @returns {Promise<Array>} Enhanced ideas with AI insights
 */
const generateAIEnhancedIdeas = async (notes, localIdeas) => {
  if (!process.env.GEMINI_API_KEY) {
    console.warn('GEMINI_API_KEY not set, returning local ideas only');
    return localIdeas;
  }

  // Don't call Gemini if user has very few notes
  if (!notes || notes.length < 3) {
    console.warn('Not enough notes for AI enhancement, returning local ideas only');
    return localIdeas;
  }

  try {
    if (!model) {
      console.warn('Gemini model not initialized');
      return localIdeas;
    }

    const noteSummary = notes
      .slice(0, 10)
      .map((n, i) => `- ${i === 0 ? '[MOST RECENT] ' : ''}${n.title}: ${n.content ? n.content.substring(0, 200) : ''}`)
      .join('\n');

    const localIdeasSummary = localIdeas
      .map(idea => `• ${idea.title}: ${idea.description}`)
      .join('\n');

    const prompt = `You are an expert at identifying innovative project ideas and career development opportunities.

The user has the following notes and knowledge areas:
${noteSummary}

Based on this knowledge, I've generated these initial ideas:
${localIdeasSummary}

Please:
1. Review these ideas and suggest 2-3 NEW ideas that haven't been mentioned
2. At least one idea must directly incorporate or build upon the [MOST RECENT] note
3. For each new idea, provide: title, brief description, required technologies, and confidence level (0-100)
4. Consider unique angles like: market demand, career growth, open-source potential, or novel combinations of skills
5. Format your response as JSON array with objects containing: title, description, technologies (array), confidence

Return ONLY valid JSON, no markdown formatting or extra text.`;

    console.log('Calling Gemini API for idea generation...');
    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    console.log('Gemini response received');

    // Parse JSON from response
    let aiIdeas = [];
    try {
      aiIdeas = JSON.parse(responseText);
    } catch (e) {
      // Try to extract JSON from markdown code blocks
      const jsonMatch = responseText.match(/```json\n([\s\S]*?)\n```/);
      if (jsonMatch) {
        aiIdeas = JSON.parse(jsonMatch[1]);
      } else {
        console.warn('Failed to parse Gemini response:', e.message);
        console.log('Raw response:', responseText);
        return localIdeas;
      }
    }

    // Transform AI ideas to match our format
    const formattedAIIdeas = aiIdeas.map((idea, index) => ({
      id: `gemini-${index}`,
      title: idea.title,
      description: idea.description,
      technologies: idea.technologies || [],
      relatedNoteIds: [],
      confidence: idea.confidence || 75,
      type: 'ai-generated',
      source: 'gemini'
    }));

    // Combine local and AI ideas, removing duplicates
    return [...localIdeas, ...formattedAIIdeas].slice(0, 8);
  } catch (error) {
    console.error('Error generating AI ideas:', error);
    console.error('Error details:', error.message);
    console.error('Error status:', error.status);
    // Fallback to local ideas if API fails
    return localIdeas;
  }
};

/**
 * Get AI enhancement for a single idea
 * @param {Object} idea - Idea to enhance
 * @param {Array} notes - User's notes for context
 * @returns {Promise<Object>} Enhanced idea with additional insights
 */
const enhanceIdea = async (idea, notes) => {
  if (!process.env.GEMINI_API_KEY) {
    return idea;
  }

  try {
    const noteTags = notes.flatMap(n => n.tags || []).slice(0, 10).join(', ');

    const prompt = `Given this project idea: "${idea.title}"
Description: "${idea.description}"
User's skills/tags: ${noteTags}

Provide a brief implementation roadmap (3-5 steps) and a 1-2 sentence market insight. Format as JSON:
{"roadmap": [...], "marketInsight": "..."}`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();

    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const enhancement = JSON.parse(jsonMatch[0]);
      return {
        ...idea,
        roadmap: enhancement.roadmap,
        marketInsight: enhancement.marketInsight
      };
    }

    return idea;
  } catch (error) {
    console.error('Error enhancing idea:', error.message);
    return idea;
  }
};

module.exports = {
  generateAIEnhancedIdeas,
  enhanceIdea
};
